{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-fpm.fullname" . }}-secrets
  labels:
    {{- include "wordpress-fpm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.wordpressDbHost }}
  WORDPRESS_DB_HOST: {{ .Values.secrets.wordpressDbHost | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.wordpressDbPassword }}
  WORDPRESS_DB_PASSWORD: {{ .Values.secrets.wordpressDbPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.wordpressDbUser }}
  WORDPRESS_DB_USER: {{ .Values.secrets.wordpressDbUser | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.wordpressDbName }}
  WORDPRESS_DB_NAME: {{ .Values.secrets.wordpressDbName | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.sslRootCA }}
  ca.pem: {{ .Values.secrets.sslRootCA | quote }}
  {{- end }}
  {{- if .Values.secrets.sshPrivateKey }}
  wp.pem: {{ .Values.secrets.sshPrivateKey | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.externalSecrets.enabled (eq .Values.externalSecrets.secretStore.name "local-vault")}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-fpm.fullname" . }}-secrets
  labels:
    {{- include "wordpress-fpm.labels" . | nindent 4 }}
type: Opaque
stringData:
{{ .Files.Get .Values.externalSecrets.secretStore.secretFile | indent 2 }}  
{{- end }}