apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payload-cms.fullname" . }}-config
  labels:
    {{- include "payload-cms.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  NEXT_TELEMETRY_DISABLED: {{ .Values.config.nextTelemetryDisabled | quote }}
  PORT: {{ .Values.config.port | quote }}
  BREVO_EMAILS_ACTIVE: {{ .Values.config.brevoEmailsActive | quote }}
  BREVO_SENDER_NAME: {{ .Values.config.brevoSenderName | quote }}
  PAYLOAD_PUBLIC_STRIPE_IS_TEST_KEY: {{ .Values.config.payloadPublicStripeIsTestKey | quote }}
  NEXT_PUBLIC_SERVER_URL: {{ .Values.config.nextPublicServerUrl | quote }}
  NEXT_PUBLIC_PAYLOAD_AUTH_URL: {{ .Values.config.nextPublicPayloadAuthUrl | quote }}
  NEXT_PUBLIC_STRIPE_PK: {{ .Values.config.nextPublicStripePk | quote }}